  
version: '3.7'

services:
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/code
      - /code/node_modules
    depends_on:
      - db
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/code
      - /code/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - server

volumes:
  mongo_data: